# Generated by Django 3.2.6 on 2021-08-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=300)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('zip_code', models.IntegerField()),
                ('home_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('office_phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('hint_question', models.CharField(max_length=100)),
                ('hint_answer', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
